import { Word, WordCategory } from '../types';

// [word, partOfSpeech, meaning, level, phonetic] — generated by scripts/build-wordbanks.mjs
export type WordBankRow = [string, string, string, number, string];

export const BANK_CATEGORIES = ['junior', 'highschool', 'toeic', 'toefl', 'business', 'daily'] as const;
export type BankCategory = (typeof BANK_CATEGORIES)[number];

const BANK_LOADERS: Record<BankCategory, () => Promise<{ default: unknown }>> = {
  junior: () => import('../data/wordbanks/junior.json'),
  highschool: () => import('../data/wordbanks/highschool.json'),
  toeic: () => import('../data/wordbanks/toeic.json'),
  toefl: () => import('../data/wordbanks/toefl.json'),
  business: () => import('../data/wordbanks/business.json'),
  daily: () => import('../data/wordbanks/daily.json'),
};

const BANK_ID_PREFIX: Record<BankCategory, string> = {
  junior: 'wb_jh_',
  highschool: 'wb_hs_',
  toeic: 'wb_tc_',
  toefl: 'wb_tf_',
  business: 'wb_bz_',
  daily: 'wb_dl_',
};

export const isBankWordId = (id: string) => id.startsWith('wb_');

const slug = (word: string) =>
  word.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const rowToWord = (row: WordBankRow, category: BankCategory): Word => {
  const [word, partOfSpeech, meaning, level, phonetic] = row;
  return {
    id: `${BANK_ID_PREFIX[category]}${slug(word)}`,
    word,
    phonetic: phonetic || `/${word.toLowerCase()}/`,
    partOfSpeech: partOfSpeech || 'n.',
    meaning,
    exampleEn: '',
    exampleZh: '',
    confusionNotes: '',
    category: category as WordCategory,
    level,
    repetition: 0,
    easeFactor: 2.5,
    intervalDays: 0,
    lastReviewedAt: null,
    nextReviewAt: new Date(0).toISOString(),
    consecutiveCorrect: 0,
    totalAttempts: 0,
    mistakeCount: 0,
    isWeak: false,
    status: 'new',
  };
};

const cache = new Map<BankCategory, Promise<Word[]>>();

export const loadWordBank = (category: BankCategory): Promise<Word[]> => {
  let pending = cache.get(category);
  if (!pending) {
    pending = BANK_LOADERS[category]()
      .then(mod => (mod.default as WordBankRow[]).map(row => rowToWord(row, category)))
      .catch(err => {
        cache.delete(category);
        throw err;
      });
    cache.set(category, pending);
  }
  return pending;
};

export const loadAllWordBanks = async (): Promise<Word[]> => {
  const lists = await Promise.all(BANK_CATEGORIES.map(c => loadWordBank(c).catch(() => [] as Word[])));
  return lists.flat();
};
